version: '3.3'
services:
    autoqnn-pytorch-jupyterhub:
        build:
           context: ./Docker
           dockerfile: Dockerfile
        image: "jupyterhub-autoqnn-pytorch:v1.0"
        ports:
            - '18889:8000'
            - '18223:22'
        volumes:
            - "/home:/home"
            - "/home/gongcheng/datasets:/open_datasets:ro"
            - "/mnt/f/Windows/Work/Database/Models:/open_models:ro"
            - "./:/workspace"
            # - "./models:/local_models"
            # - "./datasets:/local_datasets"
            # - "./motd:/etc/motd"

        shm_size: "4gb"
        #runtime: nvidia  # 启用NVIDIA运行时，启用GPU支持
        deploy:
           resources:
               reservations:
                   devices:
                       - driver: nvidia
                         device_ids: ['0','1']
                         capabilities: [gpu]
        container_name: jupyterhub-autoqnn-pytorch-v2
        #command: "/etc/init.d/ssh start && /etc/init.d/ssh status && jupyterhub -f /etc/.jupyter_config/jupyterhub_config.py --port 8000"
        command: ["/bin/bash", "-c", "/etc/init.d/ssh start && jupyterhub -f /etc/.jupyter_config/jupyterhub_config.py --port 8000"]
        restart: unless-stopped